### ISSUE TITLE
Hacer el código que detecte si una string es una cadena DET-NOM-ADJ en español

### ISSUE THREAD

**Issue by nimbusaeta** [Lingwars/programacion-idiota#2]

**Comment by nea-glossa** [comment]
Hola! Un par de cuestiones. 
La primera es que he hecho el código en un notebook de jupyter (.ipynb) . ¿Subo directamente el notebook o hago mejor un documento .py?
Y lo segundo, ¿tengo permisos para subir cosas o como funciona esto?

**Comment by nea-glossa** [comment]
Por cierto el código no hace exactamente lo de dar TRUE o FALSE sino que básicamente el matcher ya te guarda automáticamente todos los matches y yo solo tengo que hacer print() con los resultados. Cuando lo suba lo verás.

**Comment by nimbusaeta** [comment]
> 
> 
> Hola! Un par de cuestiones.
> La primera es que he hecho el código en un notebook de jupyter (.ipynb) . ¿Subo directamente el notebook o hago mejor un documento .py?
> Y lo segundo, ¿tengo permisos para subir cosas o como funciona esto?

Mejor un .py. Ya tienes permisos :)

**Comment by nimbusaeta** [comment]
> 
> 
> Por cierto el código no hace exactamente lo de dar TRUE o FALSE sino que básicamente el matcher ya te guarda automáticamente todos los matches y yo solo tengo que hacer print() con los resultados. Cuando lo suba lo verás.

Ok! Pues reescribimos el issue. Es que tenía que poner algún título y me gustaría que siempre fueran muy concretos para evitar al máximo posibles malentendidos :)

**Comment by nea-glossa** [comment]
Cierro este issue.
